### ISSUE TITLE
Styled-components class not attached to element

### ISSUE THREAD

**Issue by ivis-simwave** [luukdv/hamburger-react#32]
Good day,

thank you for creating this library, it looks nice!

I would like to show it only on a small screen size while using Styled-components. I therefore tried to instantiate the Hamburger as follows:

```
const StyledHamburger = styled(Hamburger)`
	@media(min-width: 770px){
		display: none;
	}
`;
```

However, as the className is not attached to the element, this does not work. See the [Styled-components](https://styled-components.com/docs/basics#styling-any-component) documentation for more information.

**Comment by luukdv** [comment]
Hi!

The reason for not passing a `className` is because it could be error-prone, with users accidentally overwriting required styles. I realized a while ago this might not be the best reasoning though, so in the next breaking version I'll change this. Until that moment, you could wrap the component in a `<div>` on which you apply these styles, or use the `.hamburger-react` className manually.

**Comment by ivis-simwave** [comment]
Thanks for the quick reply! I did figure something like that and have indeed used the .hamburger-react className to get it done. I am looking forward to the next version!
